CREATE TABLE IF NOT EXISTS USUARIOS (
  ID NUMBER(19) PRIMARY KEY,
  TX_NOMBRE VARCHAR2(250) NOT NULL,
  NU_EDAD NUMBER(3) NOT NULL,
  TX_EMAIL VARCHAR2(250) NOT NULL,
  TX_PASS VARCHAR2(256) NOT NULL
);